// <auto-generated />
using System;
using BetTime.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetTime.Data.Migrations
{
    [DbContext(typeof(BetTimeContext))]
    [Migration("20251213214423_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BetTime.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MarketSelectionId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Won")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MarketSelectionId");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BetTime.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LaLiga",
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bundesliga",
                            SportId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premier League",
                            SportId = 1
                        });
                });

            modelBuilder.Entity("BetTime.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketType")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Resultado final",
                            MarketType = 0,
                            MatchId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Más/Menos de 2.5 goles",
                            MarketType = 1,
                            MatchId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Resultado final",
                            MarketType = 0,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Más/Menos de 2.5 goles",
                            MarketType = 1,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Resultado final",
                            MarketType = 0,
                            MatchId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Más/Menos de 2.5 goles",
                            MarketType = 1,
                            MatchId = 3
                        });
                });

            modelBuilder.Entity("BetTime.Models.MarketSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.ToTable("MarketSelections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarketId = 1,
                            Name = "Real Madrid gana",
                            Odd = 1.8m
                        },
                        new
                        {
                            Id = 2,
                            MarketId = 1,
                            Name = "Empate",
                            Odd = 3.2m
                        },
                        new
                        {
                            Id = 3,
                            MarketId = 1,
                            Name = "Barcelona gana",
                            Odd = 4.0m
                        },
                        new
                        {
                            Id = 4,
                            MarketId = 2,
                            Name = "Más de 2.5 goles",
                            Odd = 2.1m
                        },
                        new
                        {
                            Id = 5,
                            MarketId = 2,
                            Name = "Menos de 2.5 goles",
                            Odd = 1.7m
                        },
                        new
                        {
                            Id = 6,
                            MarketId = 3,
                            Name = "Bayern Munich gana",
                            Odd = 1.5m
                        },
                        new
                        {
                            Id = 7,
                            MarketId = 3,
                            Name = "Empate",
                            Odd = 3.5m
                        },
                        new
                        {
                            Id = 8,
                            MarketId = 3,
                            Name = "Borussia Dortmund gana",
                            Odd = 5.0m
                        },
                        new
                        {
                            Id = 9,
                            MarketId = 4,
                            Name = "Más de 2.5 goles",
                            Odd = 1.9m
                        },
                        new
                        {
                            Id = 10,
                            MarketId = 4,
                            Name = "Menos de 2.5 goles",
                            Odd = 2.0m
                        },
                        new
                        {
                            Id = 11,
                            MarketId = 5,
                            Name = "Manchester United gana",
                            Odd = 2.0m
                        },
                        new
                        {
                            Id = 12,
                            MarketId = 5,
                            Name = "Empate",
                            Odd = 3.0m
                        },
                        new
                        {
                            Id = 13,
                            MarketId = 5,
                            Name = "Liverpool gana",
                            Odd = 3.5m
                        },
                        new
                        {
                            Id = 14,
                            MarketId = 6,
                            Name = "Más de 2.5 goles",
                            Odd = 2.2m
                        },
                        new
                        {
                            Id = 15,
                            MarketId = 6,
                            Name = "Menos de 2.5 goles",
                            Odd = 1.65m
                        });
                });

            modelBuilder.Entity("BetTime.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<double>("AwayWinProbability")
                        .HasColumnType("float");

                    b.Property<double>("DrawProbability")
                        .HasColumnType("float");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<int>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<double>("HomeWinProbability")
                        .HasColumnType("float");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayCorners = 0,
                            AwayScore = 0,
                            AwayTeamId = 2,
                            AwayWinProbability = 0.0,
                            DrawProbability = 0.0,
                            DurationMinutes = 90,
                            Finished = false,
                            HomeCorners = 0,
                            HomeScore = 0,
                            HomeTeamId = 1,
                            HomeWinProbability = 0.0,
                            LeagueId = 1,
                            StartTime = new DateTime(2025, 12, 11, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayCorners = 0,
                            AwayScore = 0,
                            AwayTeamId = 7,
                            AwayWinProbability = 0.0,
                            DrawProbability = 0.0,
                            DurationMinutes = 90,
                            Finished = false,
                            HomeCorners = 0,
                            HomeScore = 0,
                            HomeTeamId = 6,
                            HomeWinProbability = 0.0,
                            LeagueId = 2,
                            StartTime = new DateTime(2025, 12, 11, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayCorners = 0,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            AwayWinProbability = 0.0,
                            DrawProbability = 0.0,
                            DurationMinutes = 90,
                            Finished = false,
                            HomeCorners = 0,
                            HomeScore = 0,
                            HomeTeamId = 11,
                            HomeWinProbability = 0.0,
                            LeagueId = 3,
                            StartTime = new DateTime(2025, 12, 11, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BetTime.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fútbol"
                        });
                });

            modelBuilder.Entity("BetTime.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 1,
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 1,
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 1,
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 2,
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 7,
                            LeagueId = 2,
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 8,
                            LeagueId = 2,
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = 9,
                            LeagueId = 2,
                            Name = "Bayer Leverkusen"
                        },
                        new
                        {
                            Id = 10,
                            LeagueId = 2,
                            Name = "Schalke 04"
                        },
                        new
                        {
                            Id = 11,
                            LeagueId = 3,
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 12,
                            LeagueId = 3,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 13,
                            LeagueId = 3,
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 14,
                            LeagueId = 3,
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = 15,
                            LeagueId = 3,
                            Name = "Manchester City"
                        });
                });

            modelBuilder.Entity("BetTime.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50m,
                            Date = new DateTime(2025, 12, 11, 21, 44, 23, 11, DateTimeKind.Utc).AddTicks(2598),
                            PaymentMethod = "Tarjeta",
                            Type = "DEPOSIT",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 25m,
                            Date = new DateTime(2025, 12, 12, 21, 44, 23, 11, DateTimeKind.Utc).AddTicks(2603),
                            PaymentMethod = "PayPal",
                            Type = "DEPOSIT",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100m,
                            Date = new DateTime(2025, 12, 10, 21, 44, 23, 11, DateTimeKind.Utc).AddTicks(2605),
                            PaymentMethod = "Tarjeta",
                            Type = "DEPOSIT",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50m,
                            Date = new DateTime(2025, 12, 12, 21, 44, 23, 11, DateTimeKind.Utc).AddTicks(2607),
                            PaymentMethod = "PayPal",
                            Type = "WITHDRAW",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 75m,
                            Date = new DateTime(2025, 12, 11, 21, 44, 23, 11, DateTimeKind.Utc).AddTicks(2608),
                            PaymentMethod = "Tarjeta",
                            Type = "DEPOSIT",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Amount = 30m,
                            Date = new DateTime(2025, 12, 12, 21, 44, 23, 11, DateTimeKind.Utc).AddTicks(2610),
                            PaymentMethod = "PayPal",
                            Type = "WITHDRAW",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BetTime.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 100m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juan@example.com",
                            Password = "pass123",
                            Role = "user",
                            Username = "juan123"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 150m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "albertoriveiro@hotmail.es",
                            Password = "pass456",
                            Role = "admin",
                            Username = "albertorbd"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 120m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura@example.com",
                            Password = "pass789",
                            Role = "user",
                            Username = "laura234"
                        });
                });

            modelBuilder.Entity("BetTime.Models.Bet", b =>
                {
                    b.HasOne("BetTime.Models.MarketSelection", "MarketSelection")
                        .WithMany()
                        .HasForeignKey("MarketSelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetTime.Models.Match", "Match")
                        .WithMany("Bets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BetTime.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketSelection");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetTime.Models.League", b =>
                {
                    b.HasOne("BetTime.Models.Sport", "Sport")
                        .WithMany("Leagues")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("BetTime.Models.Market", b =>
                {
                    b.HasOne("BetTime.Models.Match", "Match")
                        .WithMany("Markets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BetTime.Models.MarketSelection", b =>
                {
                    b.HasOne("BetTime.Models.Market", "Market")
                        .WithMany("Selections")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("BetTime.Models.Match", b =>
                {
                    b.HasOne("BetTime.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetTime.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetTime.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("BetTime.Models.Team", b =>
                {
                    b.HasOne("BetTime.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("BetTime.Models.Transaction", b =>
                {
                    b.HasOne("BetTime.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetTime.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("BetTime.Models.Market", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("BetTime.Models.Match", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Markets");
                });

            modelBuilder.Entity("BetTime.Models.Sport", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("BetTime.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });

            modelBuilder.Entity("BetTime.Models.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
